version: '3'

services:
  database:
    image: mysql:5.7
    container_name: Database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./misc/:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    networks:
      - Url_net

  app:
    build: .
    container_name: API
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - ./src/:/app/src
    environment:
      - PORT=3000
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=URLs_database
      - PROTOCOL=http
      - BASE_URL=localhost
    networks:
      - Url_net

networks:
  Url_net:
    driver: bridge