version: '3'

services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    volumes:
      - ./misc/:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  app:
    build: .
    container_name: API
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - ./src/:/app/src